name: Build and Release

on:
  push:
    tags:
      - '*' # Déclenché uniquement sur les tags versionnés (ex : v1.0.0)

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build for macOS targets
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mon_projet-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*
  
  build-linux-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Install dependencies for Linux or Windows
        if: matrix.target == 'x86_64-unknown-linux-gnu' || matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          sudo apt-get update || true
          sudo apt-get install build-essential mingw-w64 || true

      - name: Build for Linux/Windows targets
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Linux/Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mon_projet-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*
  
  release:
    needs:
      - build-macos
      - build-linux-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_SECRET }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./artifacts
          asset_name: binaries-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
